---
label: Posts
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: org1
  type: text
  config:
    required: false
  label: Organization-1
- name: org2
  type: text
  config:
    required: false
  label: Organization-2
- name: url
  type: text
  config:
    required: true
  label: URL
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
- name: date
  type: number
  label: Date
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: role
  type: text
  config:
    required: false
  label: Role
- name: team
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Team
- name: cover_image
  type: file
  config:
    maxSize: 64
  label: Cover Image
