---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- name: product_type
  type: text
  config:
    required: false
  label: product type
- type: text
  name: org1
  label: org1
- type: text
  name: org2
  label: org2
- type: text
  name: project-link
  label: Project Link
- type: textarea
  name: description
  label: description
- type: number
  name: year
  label: Year
- type: text
  name: role
  label: role
- type: list
  name: team
  label: team
  description: Role, Name
- type: file
  name: cover_image
  label: cover_image
pages:
- _projects/aerospace-copy.md
- _projects/aerospace.md
- _projects/health-commission-copy.md
- _projects/health-commission.md
