---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: org1
  label: org1
- type: text
  name: org2
  label: org2
- type: text
  name: url
  label: url
- type: textarea
  name: description
  label: description
- type: number
  name: date
  label: date
- type: text
  name: role
  label: role
- type: list
  name: team
  label: team
- type: file
  name: cover_image
  label: cover_image
- name: section
  type: field_group_list
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: Heading
  - name: content
    type: blocks
    label: Content
    template_types:
    - text
    - aside
    - image_single
    - project-subsection
    config:
      min: 
      max: 
  config:
    min: 
    max: 
    labelField: 
  label: Section
pages:
- _posts/2020-06-13-test.md
