---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: link
  type: text
  config:
    required: true
  label: Link
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: background_color
  type: color
  label: Background color
  config:
    required: false
    color_format: Hex
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: YYYY
    time_format: 
    display_utc: false
    export_format: YYYY
  default: '2019-07-01 04:00:00 +0000'
- name: client
  type: text
  config:
    required: false
  label: Client
  default: Center for Strategic and International Studies
- name: client_subtitle
  type: text
  config:
    required: false
  label: Client subtitle
- name: role
  type: tag_list
  default: []
  label: Role
- name: team_credits
  type: field_group_list
  fields:
  - name: name_and_role
    type: text
    config:
      required: false
    label: Name and role
  config:
    min: 
    max: 
    labelField: 
  label: Team Credits
pages:
- _projects/test-title3.md
